```         
---
title: "uso_de_internet_mundial"
format: html
editor: visual
---
```

```{r}
library(tidyverse)
library(janitor)
```

```{r}
#Creamos funcion para cargar datos
cargar_datos <- function(path) {
  df <- read_csv(path, skip = 4)
  print(names(df))
  return(df)
}
```

```{r}
internet <- cargar_datos("../data/internet_users_world_wide.csv")
paises <- read_csv("../data/metadata_countries_internet_users.csv")
```


```{r}
glimpse(internet)
```

```{r}
# Normalizamos nombres de columnas para evitar problemas con espacios y mayúsculas usando la función clean_names() del paquete janitor
internet <- internet %>% 
    clean_names()

paises <- paises %>%
    clean_names()
```

```{r}
#Ahora podemos transformar la tabla de indicadores de formato Wide a Long para tener una columna que se llame "year" y otra que contenga el valor del indicador
internet_long <- internet %>%
    pivot_longer(
        cols = -c(country_name, country_code, indicator_name, indicator_code),
        names_to = "year",
        values_to = "internet_users"
    )
```

```{r}
#Limpiamos la variable year y la convertimos a numero
library(stringr)

internet_long$year <- str_extract(internet_long$year, "\\d{4}")

internet_long$year <- as.numeric(internet_long$year)
```

```{r}
#Realizamos un left_join() para unir los indicadores con su respectiva región y grupo de ingresos.

indicadores_por_region_income <- left_join(internet_long, paises, by = "country_code")
```

```{r}
#Borramos los NA (datos faltantes) de las varables que nos conciernen para nuestro analisis
indicadores_limpia <- indicadores_por_region_income %>%
    drop_na("region","income_group") %>% 
  filter(year >= 2013, year <= 2023)

```

```{r}
# Calculamos el promedio de uso de internet por año y grupo de ingresos
resumen_indicadores <- indicadores_limpia %>%
    group_by(year, income_group, indicator_name) %>%
    summarize(
        promedio_internet = mean(internet_users, na.rm = TRUE),
        .groups = "drop"
    )
```

```{r}
# Ordenamos los niveles de ingreso jerárquicamente
resumen_indicadores$income_group <- factor(
    resumen_indicadores$income_group,
    levels = c("Low income", "Lower middle income", 
               "Upper middle income", "High income")
)
```

```{r}
#Pasamos a formato wide para que cada grupo de ingresos quede como una columna
resumen_wide <- resumen_indicadores %>%
    pivot_wider(names_from = income_group, values_from = promedio_internet) %>%
    select(year,`Low income`, `Lower middle income`, `Upper middle income`,`High income`,`indicator_name`) %>%
    arrange(year)
```

```{r}
#Cálculo de crecimiento porcentual 
crecimiento <- indicadores_limpia %>%
  group_by(income_group) %>%
  summarize(
    valor_2013 = mean(internet_users[year == 2013], na.rm = TRUE),
    valor_2023 = mean(internet_users[year == 2023], na.rm = TRUE),
    crecimiento_pct = ((valor_2023 - valor_2013) / valor_2013) * 100,
    .groups = "drop"
  )
```

```{r}
#Agrupamos para validar hipótesis
crecimiento_grupos <- crecimiento %>%
  mutate(
    grupo = case_when(
      income_group %in% c("Low income", "Lower middle income") ~ "Bajos ingresos",
      TRUE ~ "Altos ingresos"
    )
  ) %>%
  group_by(grupo) %>%
  summarize(
    crecimiento_promedio = mean(crecimiento_pct),
    .groups = "drop"
  )
```
```{r}
write_csv(resumen_wide, "../output/resultado_hipotesis.csv")
```